import os
import requests
from bs4 import BeautifulSoup
from urllib.parse import quote_plus

def get_image_urls(query, num_images=5):
    query_encoded = quote_plus(query)
    url = f"https://www.google.com/search?q={query_encoded}&source=lnms&tbm=isch"
    
    # Send an HTTP GET request
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    
    image_urls = []
    for img in soup.find_all("img"):
        img_url = img.get("src")
        if img_url and img_url.startswith("http"):
            image_urls.append(img_url)
            if len(image_urls) >= num_images:
                break
    
    return image_urls

def download_images(image_urls, folder_name, term):
    os.makedirs(folder_name, exist_ok=True)
    
    for i, img_url in enumerate(image_urls):
        try:
            response = requests.get(img_url)
            with open(os.path.join(folder_name, f'{term}{i+1}.jpg'), 'wb') as f:
                f.write(response.content)
            # print(f'Downloaded {i+1}/{len(image_urls)} images for this search')
        except Exception as e:
            print(f'Error downloading image {i+1}: {str(e)}')

if __name__ == "__main__":
    search_terms = ["Bob the Builder", "Big Bird", "SpongeBob"]
    celebrities = [
        "Taylor Swift",
        "Beyoncé",
        "Dwayne 'The Rock' Johnson",
        "Kylie Jenner",
        "Lionel Messi",
        "Cristiano Ronaldo",
        "Ariana Grande",
        "Kim Kardashian",
        "Selena Gomez",
        "LeBron James",
        "Ellen DeGeneres",
        "Justin Bieber",
        "Drake",
        "Katy Perry",
        "Oprah Winfrey",
        "Rihanna",
        "Ed Sheeran",
        "Cameron Diaz",
        "David Beckham",
        "Lady Gaga",
        "Leonardo DiCaprio",
        "Jennifer Lopez",
        "Robert Downey Jr.",
        "Tom Cruise",
        "Meryl Streep",
        "Will Smith",
        "Keanu Reeves",
        "Emma Watson",
        "Hugh Jackman",
        "Brad Pitt",
        "Angelina Jolie",
        "George Clooney",
        "Julia Roberts",
        "Matt Damon",
        "Morgan Freeman",
        "Johnny Depp",
        "Nicole Kidman",
        "Chris Hemsworth",
        "Emma Stone",
        "Mark Zuckerberg",
        "Jeff Bezos",
        "Elon Musk",
        "Bill Gates",
        "Warren Buffett",
        "Jay-Z",
        "Kanye West",
        "Robert Pattinson",
        "Gigi Hadid",
        "Chris Pratt",
        "John Legend",
        "Chrissy Teigen",
        "Miley Cyrus",
        "Emma Thompson",
        "Jessica Alba",
        "Scarlett Johansson",
        "Liam Hemsworth",
        "Hugh Grant",
        "Daniel Radcliffe",
        "Kendall Jenner",
        "Jennifer Lawrence",
        "Gwyneth Paltrow",
        "Matthew McConaughey",
        "Natalie Portman",
        "Daniel Craig",
        "Zac Efron",
        "Tom Hanks",
        "Reese Witherspoon",
        "Ellen Pompeo",
        "Ryan Reynolds",
        "Stephen Curry",
        "Serena Williams",
        "David Letterman",
        "Adele",
        "Conor McGregor",
        "Tiger Woods",
        "Snoop Dogg",
        "Justin Timberlake",
        "Gisele Bündchen",
        "Julianne Moore",
        "Sandra Bullock",
        "John Krasinski",
        "Emily Blunt",
        "Lupita Nyong'o",
        "Idris Elba",
        "Amy Schumer",
        "Harrison Ford",
        "Anne Hathaway",
        "J.K. Rowling",
        "Ricky Gervais",
        "Zayn Malik",
        "Cara Delevingne",
        "Chris Evans",
        "Jensen Ackles",
        "Ryan Gosling",
        "Tyra Banks",
        "Kate Middleton",
        "Prince William",
        "Meghan Markle",
        "Prince Harry",
        "Megan Fox",
        "Shakira",
        "Gordon Ramsay",
        "Sofia Vergara",
        "Ellie Goulding",
        "Demi Lovato",
        "James Corden",
    ]
    cartoon_characters = [
        "Mickey Mouse",
        "Minnie Mouse",
        "Donald Duck",
        "Bugs Bunny",
        "Daffy Duck",
        "Porky Pig",
        "SpongeBob SquarePants",
        "Patrick Star",
        "Squidward Tentacles",
        "Tom and Jerry",
        "Popeye",
        "Olive Oyl",
        "Scooby-Doo",
        "Shaggy Rogers",
        "Velma Dinkley",
        "Fred Flintstone",
        "Wilma Flintstone",
        "Barney Rubble",
        "Dora the Explorer",
        "Boots (Dora the Explorer)",
        "Diego (Dora the Explorer)",
        "Homer Simpson",
        "Bart Simpson",
        "Lisa Simpson",
        "Snoopy",
        "Charlie Brown",
        "Woodstock",
        "Bobby Hill",
        "Hank Hill",
        "Dale Gribble",
        "Alvin (Alvin and the Chipmunks)",
        "Simon (Alvin and the Chipmunks)",
        "Theodore (Alvin and the Chipmunks)",
        "Pikachu",
        "Ash Ketchum",
        "Misty (Pokémon)",
        "Optimus Prime",
        "Bumblebee",
        "Megatron",
        "Garfield",
        "Odie",
        "Jon Arbuckle",
        "Bart Simpson",
        "Homer Simpson",
        "Marge Simpson",
        "Rugrats",
        "Tommy Pickles",
        "Chuckie Finster",
        "Angelica Pickles",
        "Teenage Mutant Ninja Turtles",
        "Leonardo",
        "Donatello",
        "Michelangelo",
        "Winnie the Pooh",
        "Piglet",
        "Tigger",
        "My Little Pony",
        "Twilight Sparkle",
        "Rainbow Dash",
        "Pinkie Pie",
        "Sylvester the Cat",
        "Tweety Bird",
        "Elmer Fudd",
        "Sailor Moon",
        "Tuxedo Mask",
        "Sailor Mercury",
        "The Flintstones",
        "Fred Flintstone",
        "Wilma Flintstone",
        "Betty Rubble",
        "The Jetsons",
        "George Jetson",
        "Jane Jetson",
        "Judy Jetson",
        "Inspector Gadget",
        "Penny (Inspector Gadget)",
        "Brain (Inspector Gadget)",
        "Puss in Boots",
        "Felix the Cat",
        "Mighty Mouse",
        "Dudley Do-Right",
        "Rocky and Bullwinkle",
        "Rocky",
        "Bullwinkle",
        "Moomintroll",
        "Snufkin",
        "Little My",
        "Pingu",
        "Babar",
        "Arthur (Arthur)",
        "Buster Baxter",
        "D.W. Read",
        "He-Man",
        "She-Ra",
        "Skeletor",
        "Johnny Bravo",
        "Courage the Cowardly Dog",
        "Dexter (Dexter's Laboratory)",
        "Dee Dee (Dexter's Laboratory)",
        "Powerpuff Girls",
        "Blossom",
        "Bubbles",
        "Buttercup",
        "Remy (Ratatouille)",
        "Emile (Ratatouille)",
        "Mater (Cars)",
        "Woody (Toy Story)",
        "Buzz Lightyear",
        "Jessie (Toy Story)",
    ]
    animals = [
        "Lion",
        "Tiger",
        "Elephant",
        "Giraffe",
        "Zebra",
        "Kangaroo",
        "Panda",
        "Koala",
        "Gorilla",
        "Hippopotamus",
        "Cheetah",
        "Leopard",
        "Polar Bear",
        "Grizzly Bear",
        "Black Bear",
        "Red Panda",
        "Penguin",
        "Dolphin",
        "Orca",
        "Seal",
        "Humpback Whale",
        "Wolf",
        "Fox",
        "Bear",
        "Jaguar",
        "Ocelot",
        "Puma",
        "Rabbit",
        "Hare",
        "Squirrel",
        "Chipmunk",
        "Raccoon",
        "Red Fox",
        "Koala",
        "Kookaburra",
        "Kangaroo",
        "Dingo",
        "Platypus",
        "Emu",
        "Duck-billed Platypus",
        "Galah",
        "Cockatoo",
        "Koala",
        "Wombat",
        "Crocodile",
        "Alligator",
        "Caiman",
        "Hippopotamus",
        "Rhino",
        "Warthog",
        "Meerkat",
        "Armadillo",
        "Sloth",
        "Aardvark",
        "Giraffe",
        "Okapi",
        "Antelope",
        "Gazelle",
        "Bison",
        "Buffalo",
        "Deer",
        "Elk",
        "Moose",
        "Lemur",
        "Fossa",
        "Chimpanzee",
        "Bonobo",
        "Gibbon",
        "Mandrill",
        "Capuchin Monkey",
        "Spider Monkey",
        "Koala",
        "Red Panda",
        "Fennec Fox",
        "Siberian Husky",
        "Dalmatian",
        "Poodle",
        "Golden Retriever",
        "Labrador Retriever",
        "Bulldog",
        "Siamese Cat",
        "Persian Cat",
        "Bengal Tiger",
        "White Tiger",
        "Cheetah",
        "Snow Leopard",
        "Hedgehog",
        "Porcupine",
        "Chameleon",
        "Iguana",
        "Gecko",
        "Bearded Dragon",
        "Parrot",
        "Macaw",
        "Cockatoo",
        "Canary",
        "Finch",
        "Bald Eagle",
        "Red-tailed Hawk",
        "Falcon",
        "Owl",
        "Red Fox",
        "Arctic Fox",
        "Ferret",
        "Weasel",
    ]

    num_images_per_term = 3
    output_directory = "animals"

    for term in animals:
        image_urls = get_image_urls(term, num_images=num_images_per_term)
        download_images(image_urls, output_directory, term)
